### ISSUE TITLE
[Suggestion] Add option to disable command deletion

### ISSUE THREAD

**Issue by tcatlas** [11TStudio/SquadStatJS#11]
I'd like to disable the command delete so we know who called it.

**Comment by LeventHAN** [comment]
### Added with the next push:

- **deleteUsersCommandOnError=true** 
 `true`(default): 
  This will delete the user's message if: 
  `Syntax is wrong`, 
  `Database connection error`
- **deleteUsersCommandOnSuccess=true**
 `true`(default): 
  This will delete the user's message if: 
  `User is EXIST and SUCCESFULLY SHOWN`,
  `Clans TOP list is EXIST and SUCCESFULLY SHOWN`
- **deleteUsersCommandOnNotFound=true**
 `true`(default): 
  This will delete the user's message if: 
  `User not Found On DB`
- **deleteUsersCommandOnTooFast=true**
 `true`(default): 
  This will delete the user's message if: 
  `User writes a command too fast / that is in cooldown`
- **deleteUsersCommandOnWrongChannel=true**
 `true`(default): 
  This will delete the user's message if: 
  `User writes a command on wrong channel`
