### ISSUE TITLE
[Bug] Clan tag not working

### ISSUE THREAD

**Issue by tcatlas** [11TStudio/SquadStatJS#13]
My clan's tag does not work in the clan search, `=B&B=`

**Comment by LeventHAN** [comment]
> My clan's tag does not work in the clan search, `=B&B=`

So you should search for an clan like this:
**!sclan `"=B&B="` optional TOP5/10** (so double or single quotes around the clan tag)
If this was the case, can you pelase run this querry in your DB:
`SELECT * FROM PlayerDied a WHERE attackerName LIKE ('%=B&B=%')`
If this gives you 0 rows as response that means the players are using some diffrent tag in game perhpas some space between `=` and `B` for example :)

**Comment by tcatlas** [comment]
None of our members use spaces in their tags. Here's the response to that query: https://i.imgur.com/uhSJTG1.png

**Comment by LeventHAN** [comment]
Fixed on Discord (PM) 💯
