### ISSUE TITLE
Add Teamkills to stats

### ISSUE THREAD

**Issue by tcatlas** [11TStudio/SquadStatJS#14]
Adding the number of teamkills a given player has doled out would make a great stat.

**Comment by LeventHAN** [comment]
I will add this once SquadJSv2 is public shared otherwise I will need to update the code twice...
I made a new branch ready waiting for SquadJSv2 👍 
I will ping you once everything is ready.

**Comment by LeventHAN** [comment]
Perhaps I can add this since now I made SquadStatJS v2 ready 😊 It would not be too much work to update the query tomorrow it will be ready probably

**Comment by LeventHAN** [comment]
Added with the last update.
