### ISSUE TITLE
Feature: Option to disable deletion of stats embed message

### ISSUE THREAD

**Issue by got2bhockey** [11TStudio/SquadStatJS#5]
Would be nice to have an option to disable the auto-deletion of embed messages. We use the stat tracking in our community as a way for people to show off to others. Because of this it's useful to keep the embed around

**Comment by LeventHAN** [comment]
Added this abilty in push [3835e50](https://github.com/11TStudio/SquadStatJS/commit/3835e5083a6ef7a8ae0fce2975716fff8c953e82)
